import { User, Student, RiskFactor, AttendanceRecord, GradeRecord, EngagementMetrics, Intervention, Appointment, Alert } from './types';

// Mock Users
export const mockUsers: User[] = [
  { id: 'adv1', name: 'Dr. Sarah Johnson', email: 'sarah.johnson@university.edu', role: 'advisor', password: 'advisor123', status: 'active', department: 'Academic Services', createdAt: '2024-02-01' },
  { id: 'adv2', name: 'Prof. Michael Chen', email: 'michael.chen@university.edu', role: 'advisor', password: 'advisor123', status: 'active', department: 'Academic Services', createdAt: '2024-01-15' },
  { id: 'fac1', name: 'Dr. Emily Roberts', email: 'emily.roberts@university.edu', role: 'faculty', password: 'faculty123', status: 'active', department: 'Computer Science', createdAt: '2024-01-20' },
  { id: 'fac2', name: 'Prof. David Martinez', email: 'david.martinez@university.edu', role: 'faculty', password: 'faculty123', status: 'active', department: 'Mathematics', createdAt: '2024-01-18' },
  { id: 'cou1', name: 'Dr. Lisa Anderson', email: 'lisa.anderson@university.edu', role: 'counselor', password: 'counselor123', status: 'active', department: 'Student Services', createdAt: '2024-02-10' },
  { id: 'cou2', name: 'Dr. James Wilson', email: 'james.wilson@university.edu', role: 'counselor', password: 'counselor123', status: 'active', department: 'Student Services', createdAt: '2024-02-05' },
  { id: 'adm1', name: 'Admin User', email: 'admin@university.edu', role: 'admin', password: 'admin123', status: 'active', createdAt: '2024-01-01' },
  { id: 'stu1', name: 'John Smith', email: 'john.smith@student.edu', role: 'student', password: 'student123', status: 'active', createdAt: '2024-09-01' },
  { id: 'stu2', name: 'Emma Davis', email: 'emma.davis@student.edu', role: 'student', password: 'student123', status: 'active', createdAt: '2024-09-01' },
  { id: 'stu3', name: 'Michael Brown', email: 'michael.brown@student.edu', role: 'student', password: 'student123', status: 'inactive', createdAt: '2024-09-01' },
  { id: 'stu4', name: 'Sarah Williams', email: 'sarah.williams@student.edu', role: 'student', password: 'student123', status: 'active', createdAt: '2024-09-01' },
  { id: 'stu5', name: 'David Lee', email: 'david.lee@student.edu', role: 'student', password: 'student123', status: 'inactive', createdAt: '2024-09-01' },
  { id: 'stu6', name: 'Jessica Martinez', email: 'jessica.martinez@student.edu', role: 'student', password: 'student123', status: 'active', createdAt: '2024-09-01' },
  { id: 'stu7', name: 'Ryan Taylor', email: 'ryan.taylor@student.edu', role: 'student', password: 'student123', status: 'inactive', createdAt: '2024-09-01' },
  { id: 'stu8', name: 'Olivia Johnson', email: 'olivia.johnson@student.edu', role: 'student', password: 'student123', status: 'active', createdAt: '2024-09-01' },
];

// Mock Students
export const mockStudents: Student[] = [
  {
    id: 'stu1',
    name: 'John Smith',
    email: 'john.smith@student.edu',
    program: 'Computer Science',
    year: 2,
    gpa: 2.3,
    riskLevel: 'high',
    riskScore: 78,
    advisorId: 'adv1',
    counselorId: 'cou1',
    facultyMentorId: 'fac1',
    joinedDate: '2024-09-01',
  },
  {
    id: 'stu2',
    name: 'Emma Davis',
    email: 'emma.davis@student.edu',
    program: 'Business Administration',
    year: 3,
    gpa: 3.2,
    riskLevel: 'medium',
    riskScore: 52,
    advisorId: 'adv1',
    facultyMentorId: 'fac2',
    joinedDate: '2024-09-01',
  },
  {
    id: 'stu3',
    name: 'Michael Brown',
    email: 'michael.brown@student.edu',
    program: 'Engineering',
    year: 1,
    gpa: 1.9,
    riskLevel: 'critical',
    riskScore: 92,
    advisorId: 'adv1',
    counselorId: 'cou1',
    facultyMentorId: 'fac1',
    joinedDate: '2025-01-15',
  },
  {
    id: 'stu4',
    name: 'Sarah Williams',
    email: 'sarah.williams@student.edu',
    program: 'Psychology',
    year: 4,
    gpa: 3.8,
    riskLevel: 'low',
    riskScore: 15,
    advisorId: 'adv2',
    joinedDate: '2023-09-01',
  },
  {
    id: 'stu5',
    name: 'David Lee',
    email: 'david.lee@student.edu',
    program: 'Computer Science',
    year: 2,
    gpa: 2.7,
    riskLevel: 'medium',
    riskScore: 48,
    advisorId: 'adv2',
    counselorId: 'cou2',
    facultyMentorId: 'fac1',
    joinedDate: '2024-09-01',
  },
  {
    id: 'stu6',
    name: 'Jessica Martinez',
    email: 'jessica.martinez@student.edu',
    program: 'Biology',
    year: 3,
    gpa: 2.1,
    riskLevel: 'high',
    riskScore: 71,
    advisorId: 'adv1',
    counselorId: 'cou2',
    joinedDate: '2024-01-10',
  },
  {
    id: 'stu7',
    name: 'Ryan Taylor',
    email: 'ryan.taylor@student.edu',
    program: 'Mathematics',
    year: 1,
    gpa: 3.5,
    riskLevel: 'low',
    riskScore: 22,
    advisorId: 'adv2',
    joinedDate: '2025-01-15',
  },
  {
    id: 'stu8',
    name: 'Olivia Johnson',
    email: 'olivia.johnson@student.edu',
    program: 'English Literature',
    year: 2,
    gpa: 2.5,
    riskLevel: 'medium',
    riskScore: 58,
    advisorId: 'adv1',
    facultyMentorId: 'fac2',
    joinedDate: '2024-09-01',
  },
];

// Risk Factors by Student
export const mockRiskFactors: Record<string, RiskFactor[]> = {
  stu1: [
    { category: 'GPA', value: 2.3, weight: 30, description: 'Below 2.5 threshold' },
    { category: 'Attendance', value: 72, weight: 25, description: '72% attendance rate' },
    { category: 'LMS Engagement', value: 45, weight: 20, description: 'Low LMS activity' },
    { category: 'Assignment Completion', value: 68, weight: 15, description: '68% completion rate' },
    { category: 'Support Service Usage', value: 10, weight: 10, description: 'Minimal support interaction' },
  ],
  stu3: [
    { category: 'GPA', value: 1.9, weight: 30, description: 'Critical GPA level' },
    { category: 'Attendance', value: 58, weight: 25, description: '58% attendance rate' },
    { category: 'LMS Engagement', value: 35, weight: 20, description: 'Very low LMS activity' },
    { category: 'Assignment Completion', value: 52, weight: 15, description: '52% completion rate' },
    { category: 'Support Service Usage', value: 5, weight: 10, description: 'No support interaction' },
  ],
};

// Attendance Records
export const mockAttendance: Record<string, AttendanceRecord[]> = {
  stu1: [
    { courseId: 'CS201', courseName: 'Data Structures', totalClasses: 30, attended: 22, percentage: 73 },
    { courseId: 'CS202', courseName: 'Algorithms', totalClasses: 28, attended: 20, percentage: 71 },
    { courseId: 'MATH301', courseName: 'Calculus II', totalClasses: 32, attended: 23, percentage: 72 },
  ],
  stu3: [
    { courseId: 'ENG101', courseName: 'Engineering Fundamentals', totalClasses: 25, attended: 14, percentage: 56 },
    { courseId: 'PHYS201', courseName: 'Physics I', totalClasses: 30, attended: 18, percentage: 60 },
    { courseId: 'MATH201', courseName: 'Calculus I', totalClasses: 28, attended: 16, percentage: 57 },
  ],
};

// Grade Records
export const mockGrades: Record<string, GradeRecord[]> = {
  stu1: [
    { courseId: 'CS101', courseName: 'Intro to Programming', grade: 'B-', points: 2.7, credits: 3, semester: 'Fall 2024' },
    { courseId: 'CS102', courseName: 'Object-Oriented Programming', grade: 'C+', points: 2.3, credits: 3, semester: 'Spring 2025' },
    { courseId: 'MATH201', courseName: 'Calculus I', grade: 'C', points: 2.0, credits: 4, semester: 'Fall 2024' },
    { courseId: 'CS201', courseName: 'Data Structures', grade: 'C', points: 2.0, credits: 3, semester: 'Spring 2025' },
  ],
  stu2: [
    { courseId: 'BUS201', courseName: 'Marketing Principles', grade: 'B+', points: 3.3, credits: 3, semester: 'Fall 2024' },
    { courseId: 'BUS202', courseName: 'Financial Accounting', grade: 'B', points: 3.0, credits: 3, semester: 'Spring 2025' },
    { courseId: 'ECON101', courseName: 'Microeconomics', grade: 'A-', points: 3.7, credits: 3, semester: 'Fall 2024' },
  ],
};

// Engagement Metrics
export const mockEngagement: Record<string, EngagementMetrics> = {
  stu1: {
    lmsLogins: 45,
    assignmentSubmissions: 18,
    forumParticipation: 8,
    supportServiceInteractions: 2,
    lastActivity: '2026-02-20',
  },
  stu2: {
    lmsLogins: 82,
    assignmentSubmissions: 26,
    forumParticipation: 15,
    supportServiceInteractions: 5,
    lastActivity: '2026-02-22',
  },
  stu3: {
    lmsLogins: 28,
    assignmentSubmissions: 12,
    forumParticipation: 3,
    supportServiceInteractions: 1,
    lastActivity: '2026-02-18',
  },
};

// Interventions
export const mockInterventions: Intervention[] = [
  {
    id: 'int1',
    studentId: 'stu1',
    type: 'Academic Tutoring',
    description: 'Weekly tutoring sessions for Data Structures course',
    assignedBy: 'adv1',
    assignedTo: 'John Smith',
    status: 'in-progress',
    createdAt: '2026-02-10',
    updatedAt: '2026-02-20',
    notes: 'Student showing improvement in recent assignments',
  },
  {
    id: 'int2',
    studentId: 'stu1',
    type: 'Counseling',
    description: 'Mental health counseling for stress management',
    assignedBy: 'adv1',
    assignedTo: 'cou1',
    status: 'in-progress',
    createdAt: '2026-02-12',
    updatedAt: '2026-02-22',
  },
  {
    id: 'int3',
    studentId: 'stu3',
    type: 'Early Alert',
    description: 'Critical risk alert - immediate intervention required',
    assignedBy: 'adv1',
    status: 'pending',
    createdAt: '2026-02-22',
    updatedAt: '2026-02-22',
    notes: 'Student at risk of academic probation',
  },
  {
    id: 'int4',
    studentId: 'stu3',
    type: 'Faculty Mentoring',
    description: 'Weekly check-ins with faculty mentor',
    assignedBy: 'adv1',
    assignedTo: 'fac1',
    status: 'in-progress',
    createdAt: '2026-02-15',
    updatedAt: '2026-02-21',
  },
  {
    id: 'int5',
    studentId: 'stu6',
    type: 'Study Skills Workshop',
    description: 'Attend study skills and time management workshop',
    assignedBy: 'adv1',
    status: 'completed',
    createdAt: '2026-02-05',
    updatedAt: '2026-02-18',
  },
];

// Appointments
export const mockAppointments: Appointment[] = [
  {
    id: 'apt1',
    studentId: 'stu1',
    advisorId: 'adv1',
    type: 'Academic Advising',
    date: '2026-02-25',
    time: '10:00 AM',
    status: 'scheduled',
    notes: 'Discuss course selection for next semester',
  },
  {
    id: 'apt2',
    studentId: 'stu3',
    advisorId: 'adv1',
    type: 'Intervention Meeting',
    date: '2026-02-24',
    time: '2:00 PM',
    status: 'scheduled',
    notes: 'Urgent meeting regarding academic performance',
  },
  {
    id: 'apt3',
    studentId: 'stu2',
    advisorId: 'adv1',
    type: 'Progress Check',
    date: '2026-02-20',
    time: '11:00 AM',
    status: 'completed',
    notes: 'Reviewed mid-semester progress',
  },
  {
    id: 'apt4',
    studentId: 'stu1',
    advisorId: 'cou1',
    type: 'Counseling Session',
    date: '2026-02-26',
    time: '3:00 PM',
    status: 'scheduled',
  },
];

// Alerts
export const mockAlerts: Alert[] = [
  {
    id: 'alert1',
    studentId: 'stu3',
    studentName: 'Michael Brown',
    type: 'Critical GPA',
    title: 'Critical GPA Alert',
    description: 'Student has fallen below 2.0 GPA - immediate intervention required',
    severity: 'critical',
    message: 'Michael Brown has fallen below 2.0 GPA - immediate intervention required',
    timestamp: '2026-02-22T08:30:00',
    createdAt: '2026-02-22T08:30:00',
    acknowledged: false,
  },
  {
    id: 'alert2',
    studentId: 'stu1',
    studentName: 'John Smith',
    type: 'Attendance Warning',
    title: 'Attendance Warning',
    description: 'Student attendance below 75% in multiple courses',
    severity: 'high',
    message: 'John Smith attendance below 75% in multiple courses',
    timestamp: '2026-02-21T14:20:00',
    createdAt: '2026-02-21T14:20:00',
    acknowledged: true,
    acknowledgedBy: 'Dr. Sarah Johnson',
  },
  {
    id: 'alert3',
    studentId: 'stu6',
    studentName: 'Jessica Martinez',
    type: 'Low Engagement',
    title: 'Low Engagement Alert',
    description: 'Student has not logged into LMS for 5 days',
    severity: 'medium',
    message: 'Jessica Martinez has not logged into LMS for 5 days',
    timestamp: '2026-02-20T09:15:00',
    createdAt: '2026-02-20T09:15:00',
    acknowledged: true,
    acknowledgedBy: 'Dr. Sarah Johnson',
  },
  {
    id: 'alert4',
    studentId: 'stu3',
    studentName: 'Michael Brown',
    type: 'Missing Assignments',
    title: 'Missing Assignments',
    description: 'Student has 6 overdue assignments',
    severity: 'critical',
    message: 'Michael Brown has 6 overdue assignments',
    timestamp: '2026-02-23T10:00:00',
    createdAt: '2026-02-23T10:00:00',
    acknowledged: false,
  },
];

// Grade Progression Data (for charts)
export const mockGradeProgression: Record<string, Array<{ semester: string; gpa: number }>> = {
  stu1: [
    { semester: 'Fall 2024', gpa: 2.6 },
    { semester: 'Spring 2025', gpa: 2.3 },
    { semester: 'Fall 2025', gpa: 2.3 },
  ],
  stu2: [
    { semester: 'Fall 2023', gpa: 3.0 },
    { semester: 'Spring 2024', gpa: 3.1 },
    { semester: 'Fall 2024', gpa: 3.3 },
    { semester: 'Spring 2025', gpa: 3.2 },
  ],
  stu3: [
    { semester: 'Fall 2025', gpa: 2.1 },
    { semester: 'Spring 2026', gpa: 1.9 },
  ],
};